import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Subscription from '@/Components/Subscription/Subscription'
import Quote from '@/Components/Quote/Quote'
import { useState } from 'react'
import Subscribed from '@/Components/Subscribed/Subscribed'

export default function Home() {
  const [subscribed, setSubscribed] = useState(false)
  const handleSubscription = (val: boolean) => {
    setSubscribed(val)
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main + ' bg-slate-900'}>
        {subscribed ? (
          <div>
            <Subscribed></Subscribed>
          </div>
        ) : (
          <div>
            <Quote />
            <Subscription handleSubscription={handleSubscription} />
          </div>
        )}
      </main>
    </>
  )
}
